import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";
import type { SexoAve, EstadoInspeccion, GradoHematoma, UbicacionHematoma, CategoriaLesion } from "@/generated/prisma/enums";

type Registro = {
  id: string;
  jornadaId: string | null;
  fecha: string | null;
  anio: number | null;
  mes: number | null;
  semana: number | null;
  campania: string | null;
  clienteId: string | null;
  verificadorId: string | null;
  metaPorcentaje: number;
  plantelId: string | null;
  galpon: string | null;
  sexo: SexoAve | null;
  jabas: number | null;
  cantidad: number;
  promVivo: number | null;
  promBeneficiado: number | null;
  nroGuia: string | null;
  complex: string | null;
  observaciones: string | null;
  tempPlataforma: number | null;
  tempCamion: number | null;
  tempAves: number | null;
  hematomasCon: number | null;
  hematomasSin: number | null;
  pigNivel0: number;
  pigNivel1: number;
  pigNivel2: number;
  pigNivel3: number;
  pigNivel4: number;
  pigNivel5: number;
  pigNivel6: number;
  pigNivel7: number;
  mermaAlaKg: number | null;
  mermaPiernaKg: number | null;
  estado: EstadoInspeccion;
  pasoActual: number;
  soloLesionPigmentacion: boolean;
  createdAt: string;
  updatedAt: string;
  defectos: { tipoDefectoId: string; unidades: number; kg: number }[];
  fotos: { path: string; descripcion: string | null; latitud: number | null; longitud: number | null; createdAt: string }[];
  hematomaDetalles: { grado: GradoHematoma; ubicacion: UbicacionHematoma; cantidad: number }[];
  evaluacionesLesion: { categoria: CategoriaLesion; sexo: SexoAve; muestra: number; sinLesion: number; leve: number; grave: number }[];
};

// Restaura las 17 inspecciones que se eliminaron el 22/06 al fusionar pares
// duplicados del histórico (ver merge-ambiguous-pairs). Idempotente: si el id
// ya existe, lo informa como "ya-existe" sin tocarlo.
const REGISTROS: Registro[] = [
  {
    "id": "cmqoo6lks034c3xls38u563lb",
    "jornadaId": null,
    "fecha": "2024-06-01T00:00:00.000Z",
    "anio": 2024,
    "mes": 6,
    "semana": 22,
    "campania": null,
    "clienteId": "cmqile1y7000v36n15gdow17i",
    "verificadorId": null,
    "metaPorcentaje": 0.6,
    "plantelId": "cmqile27y003736n17d0r7l8w",
    "galpon": "10B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 2208,
    "promVivo": 3.22,
    "promBeneficiado": 2.92,
    "nroGuia": "204-00000192",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:37.756Z",
    "updatedAt": "2026-06-22T03:42:37.756Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6lkx034d3xlss3jt0fj0",
    "jornadaId": null,
    "fecha": "2024-06-01T00:00:00.000Z",
    "anio": 2024,
    "mes": 6,
    "semana": 22,
    "campania": null,
    "clienteId": "cmqile1y7000v36n15gdow17i",
    "verificadorId": null,
    "metaPorcentaje": 0.6,
    "plantelId": "cmqile27y003736n17d0r7l8w",
    "galpon": "12D",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 2043,
    "promVivo": 2.67,
    "promBeneficiado": 2.41,
    "nroGuia": "204-00000192",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:37.761Z",
    "updatedAt": "2026-06-22T03:42:37.761Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6s7307rn3xls2b3mwja1",
    "jornadaId": null,
    "fecha": "2025-04-15T00:00:00.000Z",
    "anio": 2025,
    "mes": 4,
    "semana": 16,
    "campania": "2502",
    "clienteId": "cmqile1yg000x36n1m9fb36io",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile29h003l36n10b8a3hdz",
    "galpon": "6B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 1120,
    "promVivo": 3,
    "promBeneficiado": 2.75,
    "nroGuia": "OE110-048",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:46.335Z",
    "updatedAt": "2026-06-22T03:42:46.335Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1s4000036n11w3z4iop",
        "unidades": 1,
        "kg": 2.4
      },
      {
        "tipoDefectoId": "cmqile1sp000436n1p3viwnvl",
        "unidades": 1,
        "kg": 2.9
      },
      {
        "tipoDefectoId": "cmqile1st000536n1xkf630uh",
        "unidades": 2,
        "kg": 4.25
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6s7707rr3xlsdlbo7y83",
    "jornadaId": null,
    "fecha": "2025-04-15T00:00:00.000Z",
    "anio": 2025,
    "mes": 4,
    "semana": 16,
    "campania": "2502",
    "clienteId": "cmqile1yg000x36n1m9fb36io",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile29h003l36n10b8a3hdz",
    "galpon": "1B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1260,
    "promVivo": 2.54,
    "promBeneficiado": 2.29,
    "nroGuia": "OE110-048",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:46.339Z",
    "updatedAt": "2026-06-22T03:42:46.339Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sp000436n1p3viwnvl",
        "unidades": 1,
        "kg": 2.05
      },
      {
        "tipoDefectoId": "cmqile1st000536n1xkf630uh",
        "unidades": 2,
        "kg": 4.25
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6s6w07rh3xls6r6za5vi",
    "jornadaId": null,
    "fecha": "2025-04-15T00:00:00.000Z",
    "anio": 2025,
    "mes": 4,
    "semana": 16,
    "campania": "2502",
    "clienteId": "cmqile1yz001136n1nw8s75l5",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile29h003l36n10b8a3hdz",
    "galpon": "6B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 546,
    "promVivo": 2.94,
    "promBeneficiado": 2.69,
    "nroGuia": "T179-238",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:46.328Z",
    "updatedAt": "2026-06-22T03:42:46.328Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 1,
        "kg": 2.72
      },
      {
        "tipoDefectoId": "cmqile1sx000636n1hnl1hy78",
        "unidades": 2,
        "kg": 5.3
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6s6z07rk3xlsprpogexh",
    "jornadaId": null,
    "fecha": "2025-04-15T00:00:00.000Z",
    "anio": 2025,
    "mes": 4,
    "semana": 16,
    "campania": "2502",
    "clienteId": "cmqile1yz001136n1nw8s75l5",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile29h003l36n10b8a3hdz",
    "galpon": "1B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 657,
    "promVivo": 2.4,
    "promBeneficiado": 2.15,
    "nroGuia": "T179-238",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:46.331Z",
    "updatedAt": "2026-06-22T03:42:46.331Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 1,
        "kg": 2.2
      },
      {
        "tipoDefectoId": "cmqile1sx000636n1hnl1hy78",
        "unidades": 1,
        "kg": 2.26
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo6vnh0a413xlss8cwd77c",
    "jornadaId": null,
    "fecha": "2025-08-25T00:00:00.000Z",
    "anio": 2025,
    "mes": 8,
    "semana": 35,
    "campania": "2504",
    "clienteId": "cmqile1x7000n36n1ch00x2f4",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile23s002536n1e0p9cwtn",
    "galpon": "6B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 2216,
    "promVivo": 3.57,
    "promBeneficiado": 3.27,
    "nroGuia": "T173-416",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:50.813Z",
    "updatedAt": "2026-06-22T03:42:50.813Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo70sp0djl3xls8d8riq2c",
    "jornadaId": null,
    "fecha": "2026-02-05T00:00:00.000Z",
    "anio": 2026,
    "mes": 2,
    "semana": 6,
    "campania": "2601",
    "clienteId": "cmqile1z7001336n1073hcpgb",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile1zy001936n1pjkaepb8",
    "galpon": "10C",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 750,
    "promVivo": 2.35,
    "promBeneficiado": 2.1,
    "nroGuia": "OE129-172",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:57.481Z",
    "updatedAt": "2026-06-22T03:42:57.481Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 2,
        "kg": 3.65
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo70y10dlx3xls8y4it1o8",
    "jornadaId": null,
    "fecha": "2026-02-09T00:00:00.000Z",
    "anio": 2026,
    "mes": 2,
    "semana": 7,
    "campania": "2601",
    "clienteId": "cmqile1xb000o36n1hxqld0jj",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile23o002436n1ih651ytc",
    "galpon": "2B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 1820,
    "promVivo": 3.02,
    "promBeneficiado": 2.73,
    "nroGuia": "OE-034-149",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:57.673Z",
    "updatedAt": "2026-06-22T03:42:57.673Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1s4000036n11w3z4iop",
        "unidades": 2,
        "kg": 5
      },
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 11,
        "kg": 23.2
      },
      {
        "tipoDefectoId": "cmqile1sp000436n1p3viwnvl",
        "unidades": 1,
        "kg": 1.9
      },
      {
        "tipoDefectoId": "cmqile1st000536n1xkf630uh",
        "unidades": 3,
        "kg": 6.8
      },
      {
        "tipoDefectoId": "cmqile1t1000736n1vfht7xd5",
        "unidades": 3,
        "kg": 6.6
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo70y50dm33xlsomvde2rv",
    "jornadaId": null,
    "fecha": "2026-02-09T00:00:00.000Z",
    "anio": 2026,
    "mes": 2,
    "semana": 7,
    "campania": "2601",
    "clienteId": "cmqile1xb000o36n1hxqld0jj",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile1zy001936n1pjkaepb8",
    "galpon": "24B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1080,
    "promVivo": 2.33,
    "promBeneficiado": 2.08,
    "nroGuia": "OE-129-283",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:57.677Z",
    "updatedAt": "2026-06-22T03:42:57.677Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sg000236n1ielvhsl9",
        "unidades": 25,
        "kg": 34.35
      },
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 4,
        "kg": 7.45
      },
      {
        "tipoDefectoId": "cmqile1sx000636n1hnl1hy78",
        "unidades": 1,
        "kg": 1.75
      },
      {
        "tipoDefectoId": "cmqile1t1000736n1vfht7xd5",
        "unidades": 3,
        "kg": 5.95
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo70y90dm83xlsluowuina",
    "jornadaId": null,
    "fecha": "2026-02-09T00:00:00.000Z",
    "anio": 2026,
    "mes": 2,
    "semana": 7,
    "campania": "2601",
    "clienteId": "cmqile1y7000v36n15gdow17i",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile23o002436n1ih651ytc",
    "galpon": "10D",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 1638,
    "promVivo": 3,
    "promBeneficiado": 2.7,
    "nroGuia": "T078-6347",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:57.681Z",
    "updatedAt": "2026-06-22T03:42:57.681Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1s4000036n11w3z4iop",
        "unidades": 2,
        "kg": 5.15
      },
      {
        "tipoDefectoId": "cmqile1sx000636n1hnl1hy78",
        "unidades": 1,
        "kg": 2.65
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo70yd0dmb3xlsa69sjpep",
    "jornadaId": null,
    "fecha": "2026-02-09T00:00:00.000Z",
    "anio": 2026,
    "mes": 2,
    "semana": 7,
    "campania": "2601",
    "clienteId": "cmqile1y7000v36n15gdow17i",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile20b001c36n1uax6rizt",
    "galpon": "3A",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1359,
    "promVivo": 2.42,
    "promBeneficiado": 2.17,
    "nroGuia": "T291-1659",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:57.685Z",
    "updatedAt": "2026-06-22T03:42:57.685Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sk000336n1xfdvozi9",
        "unidades": 2,
        "kg": 3.75
      },
      {
        "tipoDefectoId": "cmqile1sx000636n1hnl1hy78",
        "unidades": 1,
        "kg": 2.05
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo72qg0esp3xlslm0bptt6",
    "jornadaId": null,
    "fecha": "2026-03-29T00:00:00.000Z",
    "anio": 2026,
    "mes": 3,
    "semana": 13,
    "campania": "2601",
    "clienteId": "cmqile1xy000t36n1l9x0zg4y",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile2a6003r36n1lvooxm79",
    "galpon": "9B",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 2128,
    "promVivo": 2.8,
    "promBeneficiado": 2.5,
    "nroGuia": "T155-610",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:59.992Z",
    "updatedAt": "2026-06-22T03:42:59.992Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo72pe0erz3xlsylfgti3h",
    "jornadaId": null,
    "fecha": "2026-03-29T00:00:00.000Z",
    "anio": 2026,
    "mes": 3,
    "semana": 13,
    "campania": "2601",
    "clienteId": "cmqile1xy000t36n1l9x0zg4y",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile2ar003w36n1qi6o603g",
    "galpon": "10B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1763,
    "promVivo": 2.25,
    "promBeneficiado": 2,
    "nroGuia": "T205-702",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:59.954Z",
    "updatedAt": "2026-06-22T03:42:59.954Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo72ph0es03xls5hdeacgp",
    "jornadaId": null,
    "fecha": "2026-03-29T00:00:00.000Z",
    "anio": 2026,
    "mes": 3,
    "semana": 13,
    "campania": "2601",
    "clienteId": "cmqile1y3000u36n1n994d90s",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile2a6003r36n1lvooxm79",
    "galpon": "9C",
    "sexo": "MACHO",
    "jabas": null,
    "cantidad": 1428,
    "promVivo": 2.8,
    "promBeneficiado": 2.5,
    "nroGuia": "T155-612",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:59.957Z",
    "updatedAt": "2026-06-22T03:42:59.957Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo72pl0es13xlsnnrswa4o",
    "jornadaId": null,
    "fecha": "2026-03-29T00:00:00.000Z",
    "anio": 2026,
    "mes": 3,
    "semana": 13,
    "campania": "2601",
    "clienteId": "cmqile1y3000u36n1n994d90s",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile2ar003w36n1qi6o603g",
    "galpon": "7B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1413,
    "promVivo": 2.27,
    "promBeneficiado": 2,
    "nroGuia": "T205-706",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:42:59.961Z",
    "updatedAt": "2026-06-22T03:42:59.961Z",
    "defectos": [],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  },
  {
    "id": "cmqoo736s0f2l3xlsz3wl1y1r",
    "jornadaId": null,
    "fecha": "2026-04-14T00:00:00.000Z",
    "anio": 2026,
    "mes": 4,
    "semana": 16,
    "campania": "2602",
    "clienteId": "cmqile1ym000y36n1lhfiptus",
    "verificadorId": null,
    "metaPorcentaje": 0,
    "plantelId": "cmqile21d001l36n1buonsdl4",
    "galpon": "13B",
    "sexo": "HEMBRA",
    "jabas": null,
    "cantidad": 1575,
    "promVivo": 2.6,
    "promBeneficiado": 2.35,
    "nroGuia": "OE124-554",
    "complex": null,
    "observaciones": null,
    "tempPlataforma": null,
    "tempCamion": null,
    "tempAves": null,
    "hematomasCon": null,
    "hematomasSin": null,
    "pigNivel0": 0,
    "pigNivel1": 0,
    "pigNivel2": 0,
    "pigNivel3": 0,
    "pigNivel4": 0,
    "pigNivel5": 0,
    "pigNivel6": 0,
    "pigNivel7": 0,
    "mermaAlaKg": null,
    "mermaPiernaKg": null,
    "estado": "BORRADOR",
    "pasoActual": 1,
    "soloLesionPigmentacion": false,
    "createdAt": "2026-06-22T03:43:00.580Z",
    "updatedAt": "2026-06-22T03:43:00.580Z",
    "defectos": [
      {
        "tipoDefectoId": "cmqile1sg000236n1ielvhsl9",
        "unidades": 2,
        "kg": 3.5
      },
      {
        "tipoDefectoId": "cmqile1st000536n1xkf630uh",
        "unidades": 1,
        "kg": 1.9
      },
      {
        "tipoDefectoId": "cmqile1t1000736n1vfht7xd5",
        "unidades": 1,
        "kg": 2.2
      },
      {
        "tipoDefectoId": "cmqile1ta000836n1eqm4meix",
        "unidades": 1,
        "kg": 2.1
      }
    ],
    "fotos": [],
    "hematomaDetalles": [],
    "evaluacionesLesion": []
  }
];

export async function POST() {
  const user = await getCurrentUser();
  if (!user || user.role !== "SUPERVISOR") {
    return NextResponse.json({ error: "No autorizado" }, { status: 403 });
  }

  const results: { id: string; status: string; detail?: string }[] = [];

  for (const r of REGISTROS) {
    const existe = await prisma.inspeccion.findUnique({ where: { id: r.id } });
    if (existe) {
      results.push({ id: r.id, status: "ya-existe" });
      continue;
    }
    try {
      await prisma.inspeccion.create({
        data: {
          id: r.id,
          jornadaId: r.jornadaId,
          fecha: r.fecha ? new Date(r.fecha) : null,
          anio: r.anio,
          mes: r.mes,
          semana: r.semana,
          campania: r.campania,
          clienteId: r.clienteId,
          verificadorId: r.verificadorId,
          metaPorcentaje: r.metaPorcentaje,
          plantelId: r.plantelId,
          galpon: r.galpon,
          sexo: r.sexo,
          jabas: r.jabas,
          cantidad: r.cantidad,
          promVivo: r.promVivo,
          promBeneficiado: r.promBeneficiado,
          nroGuia: r.nroGuia,
          complex: r.complex,
          observaciones: r.observaciones,
          tempPlataforma: r.tempPlataforma,
          tempCamion: r.tempCamion,
          tempAves: r.tempAves,
          hematomasCon: r.hematomasCon,
          hematomasSin: r.hematomasSin,
          pigNivel0: r.pigNivel0,
          pigNivel1: r.pigNivel1,
          pigNivel2: r.pigNivel2,
          pigNivel3: r.pigNivel3,
          pigNivel4: r.pigNivel4,
          pigNivel5: r.pigNivel5,
          pigNivel6: r.pigNivel6,
          pigNivel7: r.pigNivel7,
          mermaAlaKg: r.mermaAlaKg,
          mermaPiernaKg: r.mermaPiernaKg,
          estado: r.estado,
          pasoActual: r.pasoActual,
          soloLesionPigmentacion: r.soloLesionPigmentacion,
          createdAt: new Date(r.createdAt),
          updatedAt: new Date(r.updatedAt),
          defectos: { create: r.defectos.map((d) => ({ tipoDefectoId: d.tipoDefectoId, unidades: d.unidades, kg: d.kg })) },
          fotos: { create: r.fotos.map((f) => ({ path: f.path, descripcion: f.descripcion, latitud: f.latitud, longitud: f.longitud, createdAt: new Date(f.createdAt) })) },
          hematomaDetalles: { create: r.hematomaDetalles.map((h) => ({ grado: h.grado, ubicacion: h.ubicacion, cantidad: h.cantidad })) },
          evaluacionesLesion: { create: r.evaluacionesLesion.map((e) => ({ categoria: e.categoria, sexo: e.sexo, muestra: e.muestra, sinLesion: e.sinLesion, leve: e.leve, grave: e.grave })) },
        },
      });
      results.push({ id: r.id, status: "restaurado" });
    } catch (e) {
      results.push({ id: r.id, status: "error", detail: e instanceof Error ? e.message : String(e) });
    }
  }

  return NextResponse.json({ results });
}
